# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="example.mp3"
Content-Type: audio/mpeg

< ./example.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/f9446117-6b5b-43b0-8d6d-bad6d10e8415/transcription
Content-Type: application/json

{
  "prompt": "movimento, palhaço"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "f9446117-6b5b-43b0-8d6d-bad6d10e8415",
  "temperature": 1,
  "prompt": "Informe quantos nomes de pessoas da transcricao do video informado a seguir: '''{transcription}'''"
}